### ISSUE TITLE
Cleanup and optimize the design for handling orientation internally

### ISSUE THREAD

**Issue by himwho** [Mach1Studios/m1-orientationmanager#12]
cleanup and optimize the YPR handling, try to use quaternion more, try to to confirm our Quat->YPR is correct (does not seem perfect yet, pitch and roll are often not as expected)

**Comment by himwho** [comment]
missing feature for tracking already connected hardware devices in case they change behavior when going from a broadcast state to connected state

**Comment by TsarVul** [comment]
This task involves a refactor of M1OrientationYPR, M1OrientationQuat. 

* M1OrientationYPR should become just a M1Vector3 or something.
* M1OrientationQuat should be massively expanded upon, with a choice of constructing it with an M1Vector3 containing Euler angles.
* Orientation object shouldn't need to be able to store angles in 4 different formats, but merely a way to retrieve a normalized/denormalized/clamped version of the same Orientation object.

**Comment by himwho** [comment]
implemented here: https://github.com/Mach1Studios/m1-orientationmanager/commit/0b0b43fb002eaa1b9c98e082e6732fb650cfb5f6
