### ISSUE TITLE
Implement recenter() function

### ISSUE THREAD

**Issue by himwho** [Mach1Studios/m1-orientationmanager#18]

**Comment by TsarVul** [comment]
This task should see to integrate google/test unit tests into the orientation manager, and make use of updated M1OrientationTypes

**Comment by himwho** [comment]
implemented here: https://github.com/Mach1Studios/m1-orientationmanager/commit/0b0b43fb002eaa1b9c98e082e6732fb650cfb5f6

recenter seems to work but seems to also reset to some value set outside of the orientation_client... investigating

**Comment by himwho** [comment]
closing this and making a new issue off the little enhancement needed
